LEGAL_FACTS = [
    "IT_OUTSOURCING_WITHOUT_AUDIT",
    "IT_OUTSOURCING_PRESENT",
    "VENDOR_USED",
    "NO_VENDOR_RISK_ASSESSMENT",

    "PERSONAL_DATA_PROCESSED",
    "DATA_SHARED_WITHOUT_CONSENT",
    "CONSENT_PRESENT",

    "NO_DATA_RETENTION_POLICY",
    "PURPOSE_LIMITATION_VIOLATION",
    "NOTICE_NOT_PROVIDED"
]
